POST http://localhost:8080/api/users HTTP/1.1
content-type: application/json

{
  "username": "gerin2",
  "email": "gerin2@google.com",
  "password": ""
}

### Get user by id
GET http://localhost:8080/api/users/1 HTTP/1.1


### Get user list
GET http://localhost:8080/api/users?page=0&size=5 HTTP/1.1

